### ISSUE TITLE
Update preferences (theia @0.3.7)

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia-plantuml-extension#5]
The preferences api changed in theia @0.3.7. Those changes should be adapted. https://github.com/theia-ide/theia-plantuml-extension/commit/c578b91eab941ee7fea601d790a4fae0c81ddf3b is a starting point.

**Comment by marcdumais-work** [comment]
@AlexTugarev I just noticed this too, when I tried to build an internal docker image we use for demos. I see you started on this?
